db.url=jdbc:mysql://localhost:3306/car_rental_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.username=root
db.password=#Gaurang04#
db.driver=com.mysql.cj.jdbc.Driver

db.pool.maximumPoolSize=20
db.pool.minimumIdle=5
db.pool.connectionTimeoutMs=30000
db.pool.idleTimeoutMs=600000
db.pool.maxLifetimeMs=1800000
db.pool.leakDetectionThresholdMs=20000
db.pool.name=CarRentalPool